#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Per-trial CSV logger for the shape-target reaching task.

Samples every relevant topic at record_rate between the trial_start /
trial_end events from target_manager.py and writes
<results_dir>/trial_XXX_raw.csv. Values whose topic has been silent for more
than stale_timeout are written as NaN, so the log format is identical whether
or not the safety pipeline / device is connected.

Notes on derived columns:
  q_candidate : control_joint_angle publishes no candidate topic, so it is
                reconstructed as q_target + shape_control_error (both published
                in the same control cycle).
  gate_rejected : candidate predicted fc below the hard thresholds. Empty when
                the candidate fc topics are silent.
  mu          : normalized safety margin from the measured r_f / r_tau.

After each trial_end the metrics CSV and the summary row are produced via
compute_metrics.py; on session_end the plots are generated by
figures/plot_task.py (auto_plot).
"""

import csv
import json
import os
import subprocess
import time

import numpy as np
import rospy
from sensor_msgs.msg import JointState
from std_msgs.msg import Float64, Float64MultiArray, String, UInt8

import compute_metrics
import dragon_fk

NAN = float("nan")


class TaskRecorder:
    def __init__(self):
        rospy.init_node("task_recorder")

        self.robot_ns = rospy.get_param("~robot_ns", "dragon")
        self.device_ns = rospy.get_param("~device_ns", "/dracomancer").rstrip("/")
        base = self.device_ns + "/shape_task"
        topics = rospy.get_param("~topics", {})
        if not isinstance(topics, dict):
            topics = {}

        def topic(key, default):
            return str(topics.get(key, default))

        self.joint_names = rospy.get_param("~dragon_joint_names", list(dragon_fk.JOINT_ORDER))
        self.exo_joint_names = rospy.get_param("~exo_joint_names", [
            "shoulder_abduction_adduction_joint",
            "shoulder_flexion_extension_joint",
            "upper_arm_external_internal_rotation_joint",
            "elbow_flexion_extension_joint",
            "wrist_supination_joint",
            "wrist_flexion_extension_joint",
            "wrist_abduction_adduction_joint",
        ])
        self.n_joints = len(self.joint_names)
        self.n_exo = len(self.exo_joint_names)

        self.record_rate = float(rospy.get_param("~record_rate", 40.0))
        self.stale_timeout = float(rospy.get_param("~stale_timeout", 1.0))
        self.auto_plot = bool(rospy.get_param("~auto_plot", True))

        # Safety thresholds (fallback until the threshold topics arrive).
        self.r_f_hard = float(rospy.get_param("~r_f_hard", 0.108990))
        self.r_f_safe = float(rospy.get_param("~r_f_safe", 0.249220))
        self.r_tau_hard = float(rospy.get_param("~r_tau_hard", 0.015400))
        self.r_tau_safe = float(rospy.get_param("~r_tau_safe", 0.278159))
        self.use_threshold_topics = bool(rospy.get_param("~use_threshold_topics", True))

        # Success-condition params forwarded to compute_metrics for recomputation.
        self.metric_params = {
            "E_q_threshold": float(rospy.get_param("~E_q_threshold", 0.15)),
            "E_s_threshold": float(rospy.get_param("~E_s_threshold", 0.05)),
            "t_hold": float(rospy.get_param("~t_hold", 1.0)),
            "require_safety_margin": bool(rospy.get_param("~require_safety_margin", True)),
            "joint_names": self.joint_names,
        }

        self.link_length = float(rospy.get_param("~link_length", dragon_fk.DEFAULT_LINK_LENGTH))
        self.inter_joint_x_offset = float(rospy.get_param(
            "~inter_joint_x_offset", dragon_fk.DEFAULT_INTER_JOINT_X_OFFSET))
        self.es_normalize = bool(rospy.get_param("~E_s_normalize", False))

        # Latest values as {key: (value, stamp)}.
        self.latest = {}

        # Trial bookkeeping.
        self.results_dir = None
        self.trial = None       # trial_start payload while recording
        self.csv_file = None
        self.csv_writer = None
        self.raw_path = None
        self.plotted = False

        rospy.Subscriber(topic("q_current", "/%s/joint_states" % self.robot_ns),
                         JointState, self.make_joint_cb("q_current", self.joint_names),
                         queue_size=1)
        rospy.Subscriber(topic("q_target", "/%s/joints_ctrl" % self.robot_ns),
                         JointState, self.make_joint_cb("q_target", self.joint_names),
                         queue_size=1)
        rospy.Subscriber(topic("q_exo", self.device_ns + "/joint_states"),
                         JointState, self.make_joint_cb("q_exo", self.exo_joint_names),
                         queue_size=1)
        rospy.Subscriber(topic("shape_error", self.device_ns + "/shape_control_error"),
                         Float64MultiArray, self.make_array_cb("shape_error"), queue_size=1)
        rospy.Subscriber(topic("r_f", "/%s/debug/fc_f_min_filtered" % self.robot_ns),
                         Float64, self.make_float_cb("r_f"), queue_size=1)
        rospy.Subscriber(topic("r_tau", "/%s/debug/fc_t_min_filtered" % self.robot_ns),
                         Float64, self.make_float_cb("r_tau"), queue_size=1)
        rospy.Subscriber(topic("candidate_r_f", self.device_ns + "/candidate/fc_f_min"),
                         Float64, self.make_float_cb("cand_r_f"), queue_size=1)
        rospy.Subscriber(topic("candidate_r_tau", self.device_ns + "/candidate/fc_t_min"),
                         Float64, self.make_float_cb("cand_r_tau"), queue_size=1)
        rospy.Subscriber(topic("switch_diag", self.device_ns + "/joint_map/switch_ratio"),
                         Float64MultiArray, self.make_array_cb("switch_diag"), queue_size=1)
        rospy.Subscriber(topic("safety_scale", self.device_ns + "/dragon_shape_safety_scale"),
                         Float64, self.make_float_cb("safety_scale"), queue_size=1)
        rospy.Subscriber(topic("flight_state", "/%s/flight_state" % self.robot_ns),
                         UInt8, self.make_float_cb("flight_state"), queue_size=1)
        if self.use_threshold_topics:
            rospy.Subscriber(topic("force_threshold",
                                   self.device_ns + "/force_volume_radius_threshold"),
                             Float64MultiArray, self.force_threshold_cb, queue_size=1)
            rospy.Subscriber(topic("torque_threshold",
                                   self.device_ns + "/torque_volume_radius_threshold"),
                             Float64MultiArray, self.torque_threshold_cb, queue_size=1)
        rospy.Subscriber(base + "/event", String, self.event_cb, queue_size=10)

        rospy.on_shutdown(self.on_shutdown)
        rospy.Timer(rospy.Duration(1.0 / max(self.record_rate, 1.0)), self.sample)
        rospy.loginfo("task recorder ready (rate=%.1f Hz)", self.record_rate)

    # ------------------------------------------------------------- callbacks
    def make_joint_cb(self, key, names):
        def cb(msg):
            pos = dict(zip(msg.name, msg.position))
            vals = [pos.get(n) for n in names]
            if any(v is None for v in vals):
                return  # different producer on a shared topic name
            self.latest[key] = ([float(v) for v in vals], rospy.get_time())
        return cb

    def make_array_cb(self, key):
        def cb(msg):
            self.latest[key] = (list(msg.data), rospy.get_time())
        return cb

    def make_float_cb(self, key):
        def cb(msg):
            self.latest[key] = (float(msg.data), rospy.get_time())
        return cb

    def force_threshold_cb(self, msg):
        if len(msg.data) > 1:
            self.r_f_hard, self.r_f_safe = float(msg.data[0]), float(msg.data[1])

    def torque_threshold_cb(self, msg):
        if len(msg.data) > 1:
            self.r_tau_hard, self.r_tau_safe = float(msg.data[0]), float(msg.data[1])

    def event_cb(self, msg):
        try:
            event = json.loads(msg.data)
        except ValueError:
            rospy.logwarn("recorder: broken event JSON ignored")
            return
        kind = event.get("event")
        if kind == "session_start":
            self.results_dir = event.get("results_dir")
        elif kind == "trial_start":
            self.start_trial(event)
        elif kind == "trial_end":
            self.end_trial(event)
        elif kind == "session_end":
            self.results_dir = event.get("results_dir") or self.results_dir
            self.run_plots()

    # ------------------------------------------------------------- recording
    def columns(self):
        cols = ["time", "target_name"]
        cols += ["q_star_%d" % i for i in range(self.n_joints)]
        cols += ["q_current_%d" % i for i in range(self.n_joints)]
        cols += ["q_target_%d" % i for i in range(self.n_joints)]
        cols += ["q_candidate_%d" % i for i in range(self.n_joints)]
        cols += ["q_exo_%d" % i for i in range(self.n_exo)]
        cols += ["r_f", "r_tau", "mu", "gate_rejected", "E_q", "E_s"]
        # Extra diagnostics beyond the required minimum.
        cols += ["gate_state", "cand_r_f", "cand_r_tau", "safety_scale",
                 "flight_state", "wall_time"]
        # Roll-based pitch/yaw allocation (joint1=wrist, joint2=elbow); see
        # switch_diag_topic in control_joint_angle.py for the exact definition.
        cols += ["r1", "rho1", "c1_pitch", "c1_yaw", "r2", "rho2", "c2_pitch", "c2_yaw"]
        return cols

    def start_trial(self, event):
        if self.csv_file is not None:
            rospy.logwarn("recorder: trial_start while recording; closing previous file")
            self.close_csv()
        self.results_dir = event.get("results_dir") or self.results_dir
        if not self.results_dir:
            rospy.logerr("recorder: trial_start without results_dir; not recording")
            return
        trial_no = int(event.get("trial", 0))
        self.raw_path = os.path.join(self.results_dir, "trial_%03d_raw.csv" % trial_no)
        try:
            os.makedirs(self.results_dir, exist_ok=True)
            self.csv_file = open(self.raw_path, "w", newline="")
        except OSError as e:
            rospy.logerr("recorder: cannot open %s: %s", self.raw_path, e)
            self.csv_file = None
            return
        self.csv_writer = csv.writer(self.csv_file)
        self.csv_writer.writerow(self.columns())
        self.trial = event
        self.plotted = False
        rospy.loginfo("recording trial %d -> %s", trial_no, self.raw_path)

    def end_trial(self, event):
        if self.csv_file is None:
            return
        raw_path = self.raw_path
        trial = dict(self.trial or {})
        self.close_csv()
        info = {
            "trial": event.get("trial", trial.get("trial")),
            "target_name": event.get("target_name", trial.get("target_name")),
            "success": event.get("success"),
            "completion_time": event.get("completion_time", NAN),
            "reason": event.get("reason", ""),
        }
        try:
            metrics = compute_metrics.compute_and_write(
                raw_path, info=info, params=self.metric_params,
                summary_path=os.path.join(self.results_dir, "summary_metrics.csv"))
            rospy.loginfo("trial %s metrics: success=%s completion=%.2fs mu_min=%s",
                          info["trial"], metrics["success"],
                          metrics["completion_time"]
                          if not np.isnan(metrics["completion_time"]) else -1.0,
                          metrics["mu_min"])
        except Exception as e:
            rospy.logerr("metrics computation failed for %s: %s", raw_path, e)

    def close_csv(self):
        if self.csv_file is not None:
            try:
                self.csv_file.close()
            except OSError:
                pass
        self.csv_file = None
        self.csv_writer = None
        self.trial = None

    def fresh(self, key):
        entry = self.latest.get(key)
        if entry is None:
            return None
        value, stamp = entry
        if self.stale_timeout > 0.0 and rospy.get_time() - stamp > self.stale_timeout:
            return None
        return value

    def fresh_vec(self, key, n):
        value = self.fresh(key)
        if value is None or len(value) != n:
            return [NAN] * n
        return value

    def sample(self, _event):
        if self.csv_writer is None or self.trial is None:
            return
        now = rospy.get_time()
        q_star = self.trial.get("q_star", [NAN] * self.n_joints)
        q_cur = self.fresh_vec("q_current", self.n_joints)
        q_tgt = self.fresh_vec("q_target", self.n_joints)
        shape_err = self.fresh_vec("shape_error", self.n_joints)
        # Candidate = gated command + (raw candidate - gated command) error.
        q_cand = [t + e for t, e in zip(q_tgt, shape_err)]
        q_exo = self.fresh_vec("q_exo", self.n_exo)

        r_f = self.fresh("r_f")
        r_tau = self.fresh("r_tau")
        mu = NAN
        if r_f is not None and r_tau is not None:
            f_den = max(self.r_f_safe - self.r_f_hard, 1e-9)
            t_den = max(self.r_tau_safe - self.r_tau_hard, 1e-9)
            mu = min((r_f - self.r_f_hard) / f_den, (r_tau - self.r_tau_hard) / t_den)

        cand_f = self.fresh("cand_r_f")
        cand_t = self.fresh("cand_r_tau")
        if cand_f is None or cand_t is None:
            gate_rejected = ""  # unknown (candidate fc not published)
        else:
            gate_rejected = int(cand_f < self.r_f_hard or cand_t < self.r_tau_hard)

        if np.isnan(mu):
            gate_state = "unknown"
        elif mu < 0.0:
            gate_state = "danger"
        elif mu < 1.0:
            gate_state = "warning"
        else:
            gate_state = "safe"

        e_q = dragon_fk.joint_error(q_cur, q_star)
        e_s = dragon_fk.shape_error(q_cur, q_star, self.link_length,
                                    self.inter_joint_x_offset, self.es_normalize)

        switch_diag = self.fresh_vec("switch_diag", 8)

        row = [now, self.trial.get("target_name", "")]
        row += q_star + q_cur + q_tgt + q_cand + q_exo
        row += [r_f if r_f is not None else NAN,
                r_tau if r_tau is not None else NAN,
                mu, gate_rejected, e_q, e_s,
                gate_state,
                cand_f if cand_f is not None else NAN,
                cand_t if cand_t is not None else NAN,
                self.fresh("safety_scale") if self.fresh("safety_scale") is not None else NAN,
                self.fresh("flight_state") if self.fresh("flight_state") is not None else NAN,
                time.time()]
        row += switch_diag
        try:
            self.csv_writer.writerow(row)
        except (OSError, ValueError) as e:
            rospy.logerr_throttle(5.0, "recorder write failed: %s", e)

    # ------------------------------------------------------------- plotting
    def run_plots(self):
        if self.plotted or not self.auto_plot or not self.results_dir:
            return
        self.plotted = True
        try:
            import rospkg
            pkg = rospkg.RosPack().get_path("dracomancer")
            script = os.path.join(pkg, "figures", "plot_task.py")
            subprocess.Popen(["python3", script, self.results_dir])
            rospy.loginfo("plot generation started for %s", self.results_dir)
        except Exception as e:
            rospy.logwarn("auto plot skipped: %s", e)

    def on_shutdown(self):
        # Trial in progress at shutdown: keep the raw CSV, metrics via CLI later.
        self.close_csv()
        self.run_plots()


if __name__ == "__main__":
    try:
        TaskRecorder()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
