motor_info:
        min_pwm: 0.60 # = 1200 [ms]
        max_pwm: 0.85 # = 1700 [ms]
        min_thrust: 0 # [N]
        force_landing_thrust: 13 #[N]
        pwm_conversion_mode: 0 # SQRT Mode
        vel_ref_num: 4
        ref1:
                voltage: 25.2
                max_thrust: 19.2 # N 
                polynominal2: 0.116623913 # x10
                polynominal1: -9.709312249 # x10
                polynominal0: 17.2571166711 # x1
        ref2:
                voltage: 24.2
                max_thrust: 17.9 # N 
                polynominal2: 0.113480104 # x10
                polynominal1: -9.699259287 # x10
                polynominal0: 18.281598972 # x1
        ref3:
                voltage: 23.2
                max_thrust: 16.5 # N 
                polynominal2: 0.107786252 # x10
                polynominal1: -9.405775158 # x10
                polynominal0: 18.5482818008 # x1
        ref4:
                voltage: 22.2
                max_thrust: 16.8 # N 
                polynominal2: 0.100608300 # x10
                polynominal1: -8.821703013 # x10
                polynominal0: 17.5859729736 # x1


        # for simualtion
        rotor_damping_rate: 0.1 # = 0.001 / (0.01 + 0.001); 0.01: time constant; 0.001: dt
        rotor_force_noise: 0.1 # not sure, but good performance in gazebo
        dual_rotor_moment_noise: 0.2 # not sure, but good performance in gazebo (0.5 OK)
