servo_controller:
  state_sub_topic: servo/states
  ctrl_pub_topic: servo/target_states
  torque_pub_topic: servo/torque_enable

  gimbals:
    no_real_state: false # true if there is no servo state from real machine
    # ctrl_pub_topic: hoge # other topic than the common one:  "servo/target_states", if necessary

    angle_sgn: 1
    angle_scale: 0.001534
    zero_point_offset: 2047

    simulation:
      pid: {p: 50.0, i: 0.01, d: 0.0}
      init_value: 0.0
      type: effort_controllers/JointPositionController

    controller1:
      id: 0
      name: gimbal1_roll
    controller2:
      id: 1
      name: gimbal1_pitch
    controller3:
      id: 2
      name: gimbal2_roll
    controller4:
      id: 3
      name: gimbal2_pitch
