# robot model plugin
robot_model_plugin_name: Twin_Hammer/full_vectoring_robot_model

wrench_mat_det_thre: 0

# feasible control configuration
fc_t_min_thre: 0.01
fc_rp_min_thre: 2.2
rp_position_margin_thre: 0.1 # deprecated

edf_max_tilt: 0.05
