aerial_robot_control_name: aerial_robot_control/twin_hammer_controller

controller:

  use_haptics: false
  gimbal_roll_delta_angle: 0.1
  gimbal_pitch_delta_angle: 0.1
  gravity_acc: 3.0

  xy:
    p_gain: 3.6
    i_gain: 0.03
    d_gain: 4
    limit_sum: 10
    limit_p: 10 # [m/s^2]
    limit_i: 10 # [m/s^2]
    limit_d: 10 # [m/s^2]
    force_landing_descending_rate: -1.0

  z:
    p_gain: 2.8
    i_gain: 1.2
    d_gain: 2.8
    limit_err_p: 1.0
    limit_sum: 28 # N for clamping thrust force
    limit_p: 20 # m / s^2
    limit_i: 20 # m / s^2
    limit_d: 20 # m / s^2
    landing_err_z: -0.4
    force_landing_descending_rate: -0.5

  roll_pitch:
    p_gain: 15
    i_gain: 0.3
    d_gain: 5 # 5: good, 7: deverge in the takeoff phase
    limit_sum: 10
    limit_p: 10
    limit_i: 10
    limit_d: 10

  yaw:
    p_gain: 10
    i_gain: 0.1
    d_gain: 5
    limit_sum: 10 # N for clamping thrust force
    limit_p: 10
    limit_i: 10
    limit_d: 10
    limit_err_p: 0.4
    need_d_control: true
